### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by ghost** [HexoMod/WorldEditCUI-Forge-Edition-2#1]
When i create a world, in chat it says "Unknown command. Type /help for a list of commands" And if i type //wand or something about world edit mod, it says the same thing again. How can i make this mod work? Thanks.
Using forge 2232

**Comment by hexosse** [comment]
This is only a **client** for WorldEdit.
You must install WorldEdit first : 
Bukkit version : https://dev.bukkit.org/projects/worldedit
Forge version : https://minecraft.curseforge.com/projects/worldedit

**Comment by ghost** [comment]
oh, sorry... i just thought like "if this mod is the only world edit for released 1.11.2, then it should work alone" but the mod that you linked is released 1.11. I wouldn't open an issue if i see that. Thanks. 
And you may type a notification in the mod page that tells the user it will not work alone. Thanks again :)

**Comment by ghost** [comment]
And ah, the world edit for version 1.11 doesn't work in 1.11.2 :/ so i can't use your mod... it's sad

**Comment by hexosse** [comment]
The plugin is released under 1.11.2 but curseforge shows it at 1.11 ?
However, if you use 1.11 you can use the first edition of this mod : https://minecraft.curseforge.com/projects/worldeditcui-forge-edition

**Comment by ghost** [comment]
i am using 1.11.2. but there is only 1.11 version WorldEdit. I downloaded it to use in 1.11.2, but it didn't work.
