### ISSUE TITLE
Can not be used under Shaders Mod:MC1.11.2

### ISSUE THREAD

**Issue by sixerLiu** [HexoMod/WorldEditCUI-Forge-Edition-2#10]
When i started SEUS Renewed 1.0.0,CUI2 didn't work.

**Comment by sixerLiu** [comment]
![image](https://user-images.githubusercontent.com/12459872/44295901-4134f400-a2e5-11e8-82d0-38a2d90c9c3b.png)

**Comment by hexosse** [comment]
It's working, but outlines are dull due to the shader.
There's nothing I can do whenever a shader is used.
