### ISSUE TITLE
CUI does not display WE 7.0.0 Snapshot & Forge 14.23.5.2768 (1.12.2)

### ISSUE THREAD

**Issue by seeker2921** [HexoMod/WorldEditCUI-Forge-Edition-2#11]
With no other mods besides WE 7.0.0-Snapshot & Forge 14.23.5.2768, using WE provides no CUI visuals. No error messages are displayed on the console and no crashes occur. 

I suspect this is due to changes in forge or WE itself. The CUI likely just needs updating. As you have not updated in some time, has this mod been abandoned? Do you have the source somewhere else (since it's not on GitHub) or is it closed source?

**Comment by hexosse** [comment]
I was waiting for forge 1.13 to update and I did not try with WE 7.

I'll take a look and update the mod

**Comment by hexosse** [comment]
Just found why it doesn't work with WE7.

sk89q change the channel name from CUI to worldedit:cui

**Comment by hexosse** [comment]
OK, to use WE7 you have to update to WorldEdit CUI Forge Edition 2-2.2.0-mf-1.12.2-14.23.5.2768

(Should be approved soon)

**Comment by seeker2921** [comment]
That would do it.

Awesome job on the quick response and fix. I'll update shortly.
