### ISSUE TITLE
Doesn't work with 6.1.8

### ISSUE THREAD

**Issue by HydrogenC** [HexoMod/WorldEditCUI-Forge-Edition-2#13]
I set two pos with a wooden axe. But no CUI was shown on the screen. 
![2018-11-18_10 35 03](https://user-images.githubusercontent.com/33123710/48667989-f01fe080-eb1d-11e8-8a05-6c5539ecd929.png)

**Comment by HydrogenC** [comment]
Forge: 1.12.2-14.23.5.2768
WorldEdit: mc1.12-6.1.8-dist
FE: 2-2.2.0-mf-1.12.2-14.23.5.2768

**Comment by HydrogenC** [comment]
I opened everything. 
![2018-11-18_10 38 43](https://user-images.githubusercontent.com/33123710/48668023-8d7b1480-eb1e-11e8-8e5c-e8e548b6d345.png)

**Comment by hexosse** [comment]
If you want to use WE6 you need to use [WorldEdit CUI Forge Edition 2-2.1.2-mf-1.12.2-14.23.5.2768](https://minecraft.curseforge.com/projects/worldeditcui-forge-edition-2/files/2629417)
However, if you update to WE7 [WorldEdit CUI Forge Edition 2-2.2.0-mf-1.12.2-14.23.5.2768](https://minecraft.curseforge.com/projects/worldeditcui-forge-edition-2/files/2629418) will work as expected.

So to resume:
	WorldEdit CUI Forge Edition 2-2.1.2-mf-1.12.2-14.23.5.2768 is for WE6
	WorldEdit CUI Forge Edition 2-2.2.0-mf-1.12.2-14.23.5.2768 is for WE 7

You can find the latest version of WE here: [http://builds.enginehub.org/job/worldedit/last-successful?branch=master](http://builds.enginehub.org/job/worldedit/last-successful?branch=master)

**Comment by partyp770** [comment]
THIS FIXED MY PROBLEM! It was really hard to find the solution, though. For people like me, could you just put some big, bold disclaimer on the mod's page warning people about this issue? Or a sorta "heads up" at the bottom of the page?
