### ISSUE TITLE
Crashing on initalization

### ISSUE THREAD

**Issue by NutchapolSal** [HexoMod/WorldEditCUI-Forge-Edition-2#2]
Worldedit CUI makes Worldedit fail on mod initalization (MC crashes when approaching phase 3)
Doesn't affect other mods and the other way around
(crash report is starting minecraft with we cui and we only)
[crash-2017-03-25_00.40.32-client.txt](https://github.com/HexoMod/WorldEditCUI-Forge-Edition-2/files/868743/crash-2017-03-25_00.40.32-client.txt)
Could possibly be forge version specific
_Really want to try those new features out!_

**Comment by hexosse** [comment]
Update to the latest version as this was solved in 2.0.1

**Comment by NutchapolSal** [comment]
I guess I downloaded the 2.0.0 file just before the 2.0.1 file came out
*Closes Issue*
