### ISSUE TITLE
Set Parameter Crash

### ISSUE THREAD

**Issue by Phanabani** [HexoMod/WorldEditCUI-Forge-Edition-2#3]
When in the color settings menu, I crashed when changing the line size parameter. If you enter a single "." or include a "-" character, it will crash being unable to parse the value as a float. Values like "0." and ".5" work fine though. I tried other characters, but I think these are the only two that cause an issue.

[Crash report](https://pastebin.com/YSpnHkyb)

**Comment by hexosse** [comment]
Thanks for reporting this issue.
I'll make a correction and post a new real ease.

**Comment by hexosse** [comment]
This is solved in 2.1.1
