### ISSUE TITLE
Mod Options > WorldEditCUI

### ISSUE THREAD

**Issue by neil-bowers** [HexoMod/WorldEditCUI-Forge-Edition-2#4]
The `Config` button for WorldEditCUI under Mod Options does not work.  Clicking the button does not allow you to make any configuration changes for the mod.

As a result, how can we change the colors?  How do we get the Distance measurement in our HUD?

Otherwise the mod works as advertised.

**Comment by hexosse** [comment]
You can open the config screen after configuring your controls, not from the mods config button.
Open `Options..` then `Controls...` from the main screen and you'll find a section `WorldEdit CUI 2 Forge Edition`.

By default, you can toggle the measurer by pressing `K` and the chunk visibility by pressing `F4` while in game.

Just config a key for `Options` and you will be able to configure everything.
