### ISSUE TITLE
I have updated to the newest version

### ISSUE THREAD

**Issue by DCal661** [HexoMod/WorldEditCUI-Forge-Edition-2#5]
When I try to move I get timed out and the error says

Connection Lost

A fatal error has occurred this connection is terminated.

![error](https://user-images.githubusercontent.com/29468728/27204279-144663d2-51df-11e7-9963-315d2230d678.PNG)

I did download the latest version for 1.12

**Comment by hexosse** [comment]
I've uploaded a new version which solves this issue:  [https://minecraft.curseforge.com/projects/worldeditcui-forge-edition-2/files](https://minecraft.curseforge.com/projects/worldeditcui-forge-edition-2/files)
